force-app/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Missions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DA_VehiculeAdverseController.cls
public with sharing class DA_VehiculeAdverseController {

    @AuraEnabled(cacheable=true)
    public static List<VehicleCaseAssignment__c> getVehiculesAdverses(Id recordId) {
        if (recordId == null) return new List<VehicleCaseAssignment__c>();

        String prefix = String.valueOf(recordId).substring(0, 3);

        List<SObject> records;

        if (prefix == Schema.SObjectType.Claim__c.getKeyPrefix()) {
            records = DM002_VehicleCaseAssignment.getVehiclesAdverses(recordId);

        } else if (prefix == Schema.SObjectType.Case.getKeyPrefix()) {
            records = DM002_VehicleCaseAssignment.getVehiclesAdversesByCaseId(recordId);

        } else {
            return new List<VehicleCaseAssignment__c>();
        }

        return (List<VehicleCaseAssignment__c>) records;
    }
}