force-app/main/default/objects/Account/recordTypes/Passager.recordType-meta.xml
<RecordType>
    <fullName>Passager</fullName>
    <active>true</active>
    <label>Passager</label>
</RecordType>

force-app/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Missions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Déclarations</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseCoverage__c/CaseCoverage__c.object-meta.xml
<CustomObject>
    <label>Case Coverage</label>
    <nameField>
        <label>Case Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimCoverage__c/ClaimCoverage__c.object-meta.xml
<CustomObject>
    <label>Claim Coverage</label>
    <nameField>
        <label>Claim Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimCoverage__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Coverages</relationshipLabel>
    <relationshipName>ClaimCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/ClaimParticipant__c.object-meta.xml
<CustomObject>
    <label>Claim Participant</label>
    <nameField>
        <label>Claim Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimParticipant__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>ClaimParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Passager__c.field-meta.xml
<CustomField>
    <fullName>Passager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant de l&apos;accident</label>
    <referenceTo>Passager__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Participants de l&apos;accident</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage__c/InsurancePolicyCoverage__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy Coverage</label>
    <nameField>
        <displayFormat>COV-{00000}</displayFormat>
        <label>Insurance Policy Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Policy Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>InsurancePolicy__c</fullName>
    <label>Insurance Policy</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>InsurancePolicyCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RequestApproval__c/RequestApproval__c.object-meta.xml
<CustomObject>
    <label>Demande d&apos;approbation</label>
    <nameField>
        <displayFormat>DA-{0000}</displayFormat>
        <label>RequestApproval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RequestApprovals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/Vehicule__c.object-meta.xml
<CustomObject>
    <label>Véhicule</label>
    <nameField>
        <displayFormat>Véc-{00000}</displayFormat>
        <label>Numéro de véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Véhicules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/fields/InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>InsurancePolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Police d&apos;assurance</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipLabel>Véhicules</relationshipLabel>
    <relationshipName>vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DA_TestDataFactoryTest.cls
@isTest
private class DA_TestDataFactoryTest {

    @isTest
    static void allFactoryMethods_insertSuccessfully() {
        User u = DA_TestDataFactory.createTestUser('smk', 'Smoke', null);
        insert u;

        Account acc = DA_TestDataFactory.createTestAccount(null);
        insert acc;

        InsurancePolicy__c pol = DA_TestDataFactory.createTestPolicy(acc.Id, null);
        insert pol;

        Vehicule__c veh = DA_TestDataFactory.createTestVehicle(pol.Id, null);
        insert veh;

        Case c = DA_TestDataFactory.createTestCase(acc.Id, pol.Id, veh.Id, 'Smoke', null);
        insert c;

        Claim__c cl = DA_TestDataFactory.createTestClaim(c.Id, veh.Id, null);
        insert cl;

        Passager__c p = DA_TestDataFactory.createTestPassenger(c.Id, acc.Id, veh.Id, null);
        insert p;

        RequestApproval__c ra = DA_TestDataFactory.createTestRequestApproval(cl.Id, u.Id, u.Id, null);
        insert ra;

        InsurancePolicyCoverage__c ipc = DA_TestDataFactory.createTestInsurancePolicyCoverage(pol.Id, null);
        insert ipc;

        ClaimCoverage__c cc = DA_TestDataFactory.createTestClaimCoverage(cl.Id, ipc.Id, null);
        insert cc;

        CaseCoverage__c caco = DA_TestDataFactory.createTestCaseCoverage(c.Id, ipc.Id, null);
        insert caco;

        ClaimParticipant__c cp = DA_TestDataFactory.createTestClaimParticipant(cl.Id, acc.Id, null);
        insert cp;

        System.assertNotEquals(null, u.Id, 'User');
        System.assertNotEquals(null, acc.Id, 'Account');
        System.assertNotEquals(null, pol.Id, 'Policy');
        System.assertNotEquals(null, veh.Id, 'Vehicle');
        System.assertNotEquals(null, c.Id, 'Case');
        System.assertNotEquals(null, cl.Id, 'Claim');
        System.assertNotEquals(null, p.Id, 'Passager');
        System.assertNotEquals(null, ra.Id, 'RequestApproval');
        System.assertNotEquals(null, ipc.Id, 'InsurancePolicyCoverage');
        System.assertNotEquals(null, cc.Id, 'ClaimCoverage');
        System.assertNotEquals(null, caco.Id, 'CaseCoverage');
        System.assertNotEquals(null, cp.Id, 'ClaimParticipant');
    }
}