force-app/main/default/objects/Account/recordTypes/Passager.recordType-meta.xml
<RecordType>
    <fullName>Passager</fullName>
    <active>true</active>
    <label>Passager</label>
</RecordType>

force-app/main/default/objects/Claim__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assuré</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <formula>HYPERLINK(
    Vehicule__c,
    Vehicule__r.RegistrationNumber__c,
    &quot;_blank&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro d’immatriculation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/ClaimParticipant__c.object-meta.xml
<CustomObject>
    <label>Claim Participant</label>
    <nameField>
        <label>Claim Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimParticipant__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>ClaimParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/isDriver__c.field-meta.xml
<CustomField>
    <fullName>isDriver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Participant est conducteur ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ParticipantAccount__c.field-meta.xml
<CustomField>
    <fullName>ParticipantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nom et Prénom</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Passager__c.field-meta.xml
<CustomField>
    <fullName>Passager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant de l&apos;accident</label>
    <referenceTo>Passager__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passager assuré</fullName>
            </value>
            <value>
                <fullName>Passager adverse</fullName>
            </value>
            <value>
                <fullName>Autres partie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Participants de l&apos;accident</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/Vehicule__c.object-meta.xml
<CustomObject>
    <label>Véhicule</label>
    <nameField>
        <displayFormat>Véc-{00000}</displayFormat>
        <label>Numéro de véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Véhicules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marque</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>FORD</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/Modele__c.field-meta.xml
<CustomField>
    <fullName>Modele__c</fullName>
    <label>Modèle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/ModelePicklist__c.field-meta.xml
<CustomField>
    <fullName>ModelePicklist__c</fullName>
    <label>Modèle</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Brand__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E-Pace</fullName>
            </value>
            <value>
                <fullName>XE</fullName>
            </value>
            <value>
                <fullName>XF</fullName>
            </value>
            <value>
                <fullName>I-Pace (électrique)</fullName>
            </value>
            <value>
                <fullName>Santa Fe</fullName>
            </value>
            <value>
                <fullName>Bayon</fullName>
            </value>
            <value>
                <fullName>Ioniq 5</fullName>
            </value>
            <value>
                <fullName>Jazz</fullName>
            </value>
            <value>
                <fullName>ZR-V</fullName>
            </value>
            <value>
                <fullName>Fiesta</fullName>
            </value>
            <value>
                <fullName>Focus</fullName>
            </value>
            <value>
                <fullName>Mondeo</fullName>
            </value>
            <value>
                <fullName>Panda</fullName>
            </value>
            <value>
                <fullName>Tipo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/ProprietaireDuVehicule__c.field-meta.xml
<CustomField>
    <fullName>ProprietaireDuVehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire du véhicule</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Véhicules (Propriétaire du véhicule)</relationshipLabel>
    <relationshipName>V_hicules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <label>Numéro d&apos;immatriculation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DM_VehicleHistory.cls
/**
 * @description  : Data Manager pour l'historique des véhicules d'un passager
 * @author       : D&A Technologies
 * @date         : 2026-04-23
 */
public with sharing class DM_VehicleHistory {

    private static final String CP_FIELDS =
        'Id, isDriver__c, Roles__c, Vehicule__c, Claim__c, ' +
        'Claim__r.Name, ' +
        'Claim__r.Vehicule__c, ' +
        'Claim__r.Vehicule__r.Name, ' +
        'Claim__r.Vehicule__r.RegistrationNumber__c, ' +
        'Claim__r.Vehicule__r.Brand__c, ' +
        'Claim__r.Vehicule__r.ModelePicklist__c, ' +
        'Claim__r.Vehicule__r.Modele__c, ' +
        'Claim__r.Vehicule__r.ProprietaireDuVehicule__r.Name, ' +
        'Vehicule__r.Name, ' +
        'Vehicule__r.RegistrationNumber__c, ' +
        'Vehicule__r.Brand__c, ' +
        'Vehicule__r.ModelePicklist__c, ' +
        'Vehicule__r.Modele__c, ' +
        'Vehicule__r.ProprietaireDuVehicule__r.Name';

    private static final String CP_OBJECT = 'ClaimParticipant__c';

    public static List<ClaimParticipant__c> getParticipantsByAccount(Id accountId) {
        if (accountId == null) return new List<ClaimParticipant__c>();

        String conditions =
            'ParticipantAccount__c = \'' +
            String.escapeSingleQuotes(String.valueOf(accountId)) + '\'';

        return (List<ClaimParticipant__c>) DA_Utility.query(
            CP_FIELDS,
            CP_OBJECT,
            conditions,
            'Vehicule__r.RegistrationNumber__c ASC',
            null
        );
    }

    public static List<ClaimParticipant__c> getParticipantsByIds(Set<Id> cpIds) {
        if (cpIds == null || cpIds.isEmpty()) return new List<ClaimParticipant__c>();

        List<String> escapedIds = new List<String>();
        for (Id cpId : cpIds) {
            escapedIds.add('\'' + String.escapeSingleQuotes(String.valueOf(cpId)) + '\'');
        }
        String conditions = 'Id IN (' + String.join(escapedIds, ',') + ')';

        return (List<ClaimParticipant__c>) DA_Utility.query(
            CP_FIELDS,
            CP_OBJECT,
            conditions,
            'Vehicule__r.RegistrationNumber__c ASC',
            null
        );
    }

    public static List<ClaimParticipant__c> getParticipantsByPassager(Id accountId) {
        if (accountId == null) return new List<ClaimParticipant__c>();

        String conditions =
            'Passager__r.Account__c = \'' +
            String.escapeSingleQuotes(String.valueOf(accountId)) + '\'';

        return (List<ClaimParticipant__c>) DA_Utility.query(
            CP_FIELDS,
            CP_OBJECT,
            conditions,
            'Vehicule__r.RegistrationNumber__c ASC',
            null
        );
    }
}