force-app/main/default/objects/Account/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <label>Adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Civility__c.field-meta.xml
<CustomField>
    <fullName>Civility__c</fullName>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MaritalStatus__c.field-meta.xml
<CustomField>
    <fullName>MaritalStatus__c</fullName>
    <label>Situation familiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Célibataire</fullName>
            </value>
            <value>
                <fullName>Séparé(e)</fullName>
            </value>
            <value>
                <fullName>Divorcé(e)</fullName>
            </value>
            <value>
                <fullName>Marié(e)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MoyenNotification__c.field-meta.xml
<CustomField>
    <fullName>MoyenNotification__c</fullName>
    <label>Moyen de notification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Téléphone</fullName>
            </value>
            <value>
                <fullName>Email et Téléphone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom Complet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prenom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Féminin</fullName>
            </value>
            <value>
                <fullName>Masculin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pays__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ville</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CompagnieAdverse.recordType-meta.xml
<RecordType>
    <fullName>CompagnieAdverse</fullName>
    <active>true</active>
    <label>Compagnie Adverse</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Passager.recordType-meta.xml
<RecordType>
    <fullName>Passager</fullName>
    <active>true</active>
    <label>Passager</label>
</RecordType>

force-app/main/default/objects/Claim__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/ClaimParticipant__c.object-meta.xml
<CustomObject>
    <label>Claim Participant</label>
    <nameField>
        <label>Claim Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimParticipant__c/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <label>Adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/BirthDay__c.field-meta.xml
<CustomField>
    <fullName>BirthDay__c</fullName>
    <label>Date de Naissance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>ClaimParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/CompagnieAdverse__c.field-meta.xml
<CustomField>
    <fullName>CompagnieAdverse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compagnie adverse</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/DateDeces__c.field-meta.xml
<CustomField>
    <fullName>DateDeces__c</fullName>
    <label>Date de décès</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/IPP__c.field-meta.xml
<CustomField>
    <fullName>IPP__c</fullName>
    <label>IPP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/isDriver__c.field-meta.xml
<CustomField>
    <fullName>isDriver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Participant est conducteur ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ITT__c.field-meta.xml
<CustomField>
    <fullName>ITT__c</fullName>
    <label>ITT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/MaritalStatus__c.field-meta.xml
<CustomField>
    <fullName>MaritalStatus__c</fullName>
    <label>Situation familiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Célibataire</fullName>
            </value>
            <value>
                <fullName>Séparé(e)</fullName>
            </value>
            <value>
                <fullName>Divorcé(e)</fullName>
            </value>
            <value>
                <fullName>Marié(e)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ParticipantAccount__c.field-meta.xml
<CustomField>
    <fullName>ParticipantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nom et Prénom</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ParticipantCNI__c.field-meta.xml
<CustomField>
    <fullName>ParticipantCNI__c</fullName>
    <formula>ParticipantAccount__r.CIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays du participant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/RevenuAnnuel__c.field-meta.xml
<CustomField>
    <fullName>RevenuAnnuel__c</fullName>
    <label>Revenu annuel</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passager assuré</fullName>
            </value>
            <value>
                <fullName>Passager adverse</fullName>
            </value>
            <value>
                <fullName>Autres partie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Féminin</fullName>
            </value>
            <value>
                <fullName>Masculin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/StateOfPerson__c.field-meta.xml
<CustomField>
    <fullName>StateOfPerson__c</fullName>
    <label>Etat du Participant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indemne</fullName>
            </value>
            <value>
                <fullName>Blessé</fullName>
            </value>
            <value>
                <fullName>Décédé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/TypeContact__c.field-meta.xml
<CustomField>
    <fullName>TypeContact__c</fullName>
    <label>Type de Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Téléphone</fullName>
            </value>
            <value>
                <fullName>Mail et Téléphone</fullName>
                <default>true</default>
                <label>Mail et Téléphone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Participants de l&apos;accident</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville du participant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pays__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ville</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicule__c/Vehicule__c.object-meta.xml
<CustomObject>
    <label>Véhicule</label>
    <nameField>
        <displayFormat>Véc-{00000}</displayFormat>
        <label>Numéro de véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Véhicules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/fields/CompagnieAdverse__c.field-meta.xml
<CustomField>
    <fullName>CompagnieAdverse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compagnie adverse</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Véhicules</relationshipLabel>
    <relationshipName>Vehicules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DA_PassengerController.cls
public with sharing class DA_PassengerController {

    private static final String CLASS_NAME = DA_PassengerController.class.getName();
    private static final String ROLE_PASSAGER_ASSURE = 'Passager assuré';

            private static final String CLAIM_PARTICIPANT = 'ClaimParticipant__c';
            private static final String ACCOUNT = 'Account';

            private static final String PARTICIPANT_LIST_FIELDS =
                'Id, ParticipantCNI__c, Roles__c, isDriver__c, ' +
                'StateOfPerson__c, Pays__c, Ville__c, Sexe__c, ' +
                'ParticipantAccount__c, ParticipantAccount__r.Name, ' +
                'ParticipantAccount__r.Civility__c';

            private static final String PARTICIPANT_DETAIL_FIELDS =
                'Id, Roles__c, Sexe__c, ParticipantCNI__c, ' +
                'BirthDay__c, MaritalStatus__c, ' +
                'Pays__c, Ville__c, Adresse__c, TypeContact__c, ' +
                'StateOfPerson__c, CompagnieAdverse__c, ' +
                'ITT__c, IPP__c, DateDeces__c, RevenuAnnuel__c, ' +
                'isDriver__c, ParticipantAccount__c, ' +
                'ParticipantAccount__r.Name, ParticipantAccount__r.Nom__c, ' +
                'ParticipantAccount__r.Prenom__c, ParticipantAccount__r.Civility__c, ' +
                'ParticipantAccount__r.Email__c, ParticipantAccount__r.MoyenNotification__c';

            @AuraEnabled(cacheable=false)
            public static List<SObject> getParticipants(Id claimId) {
                if (claimId == null) {
                    throw new AuraHandledException('L\'identifiant du sinistre est requis.');
                }
                try {
                    return DM005_ClaimParticipant.getByClaimId(PARTICIPANT_LIST_FIELDS, claimId);
                } catch (Exception e) {
                    throw new AuraHandledException(e.getMessage());
                }
            }

            @AuraEnabled
            public static Map<String, Object> getParticipantById(Id participantId) {
                if (participantId == null) {
                    throw new AuraHandledException('L\'identifiant du participant est requis.');
                }
                try {
                    ClaimParticipant__c p = DM005_ClaimParticipant.getById(PARTICIPANT_DETAIL_FIELDS, participantId);
                    if (p == null) {
                        throw new AuraHandledException('Participant introuvable.');
                    }

                    Map<String, Object> result = new Map<String, Object>();
                    result.put('participantId', p.Id);
                    result.put('accountId', p.ParticipantAccount__c);
                    result.put('roles', p.Roles__c);
                    result.put('civility', p.ParticipantAccount__r.Civility__c);
                    result.put('sexe', p.Sexe__c);
                    result.put('nom', p.ParticipantAccount__r.Nom__c);
                    result.put('prenom', p.ParticipantAccount__r.Prenom__c);
                    result.put('dateNaissance', p.BirthDay__c != null ? String.valueOf(p.BirthDay__c) : '');
                    result.put('cni', p.ParticipantCNI__c);
                    result.put('situationFamiliale', p.MaritalStatus__c);
                    result.put('pays', p.Pays__c);
                    result.put('ville', p.Ville__c);
                    result.put('adresse', p.Adresse__c);
                    result.put('typeContact', p.TypeContact__c);
                    result.put('telephone', '');
                    result.put('email', p.ParticipantAccount__r.Email__c);
                    result.put('etatPassager', p.StateOfPerson__c);
                    result.put('compagnieAdverse', p.CompagnieAdverse__c);
                    result.put('itt', p.ITT__c);
                    result.put('ipp', p.IPP__c);
                    result.put('dateDeces', p.DateDeces__c != null ? String.valueOf(p.DateDeces__c) : '');
                    result.put('revenuAnnuel', p.RevenuAnnuel__c);
                    result.put('conducteur', p.isDriver__c);
                    return result;
                } catch (Exception e) {
                    throw new AuraHandledException(e.getMessage());
                }
            }

            @AuraEnabled
            public static Boolean checkDuplicate(String cin, Id claimId, Id excludeId) {
                if (String.isBlank(cin) || claimId == null) {
                    return false;
                }
                try {
                    return DM005_ClaimParticipant.existsByClaimRoleAndCIN(claimId, ROLE_PASSAGER_ASSURE, cin, excludeId);
                } catch (Exception e) {
                    throw new AuraHandledException(e.getMessage());
                }
            }

        @AuraEnabled
        public static Map<String, Object> upsertPassager(Map<String, Object> formData, Id claimId, Id vehiculeId, Boolean isUpdateMode, Id accountId) {
            Map<String, Object> response = new Map<String, Object>();

            if (claimId == null) {
                response.put('success', false);
                response.put('message', 'L\'identifiant du sinistre est requis.');
                return response;
            }

            if (accountId == null) {
                response.put('success', false);
                response.put('message', 'Le compte du participant est obligatoire.');
                return response;
            }

            try {
                ClaimParticipant__c participant;

                if (isUpdateMode && formData.get('participantId') != null) {
                    participant = new ClaimParticipant__c(
                        Id = (Id) formData.get('participantId')
                    );
                } else {
                    participant = new ClaimParticipant__c();
                    participant.Claim__c = claimId;
                    participant.Roles__c = ROLE_PASSAGER_ASSURE;
                    if (vehiculeId != null) {
                        participant.Vehicule__c = vehiculeId;
                    }
                }

                participant.ParticipantAccount__c = accountId;

                // N'écrase le rôle que s'il est explicitement fourni
                String roles = (String) formData.get('roles');
                if (String.isNotBlank(roles)) {
                    participant.Roles__c = roles;
                }

                participant.Sexe__c = (String) formData.get('sexe');
                participant.MaritalStatus__c = (String) formData.get('situationFamiliale');
                participant.Pays__c = (String) formData.get('pays');
                participant.Ville__c = (String) formData.get('ville');
                participant.Adresse__c = (String) formData.get('adresse');
                participant.TypeContact__c = (String) formData.get('typeContact');
                participant.StateOfPerson__c = (String) formData.get('etatPassager');
                participant.isDriver__c = formData.get('conducteur') == true;

                String compagnieAdverseId = (String) formData.get('compagnieAdverse');
                if (String.isNotBlank(compagnieAdverseId)) {
                    participant.CompagnieAdverse__c = (Id) compagnieAdverseId;
                }

                String dateNaissStr = (String) formData.get('dateNaissance');
                if (String.isNotBlank(dateNaissStr)) {
                    participant.BirthDay__c = Date.valueOf(dateNaissStr);
                }

                String dateDecesStr = (String) formData.get('dateDeces');
                if (String.isNotBlank(dateDecesStr)) {
                    participant.DateDeces__c = Date.valueOf(dateDecesStr);
                }

                if (formData.get('itt') != null) {
                    participant.ITT__c = Decimal.valueOf(String.valueOf(formData.get('itt')));
                }
                if (formData.get('ipp') != null) {
                    participant.IPP__c = Decimal.valueOf(String.valueOf(formData.get('ipp')));
                }
                if (formData.get('revenuAnnuel') != null) {
                    participant.RevenuAnnuel__c = Decimal.valueOf(String.valueOf(formData.get('revenuAnnuel')));
                }

                upsert participant;

                response.put('success', true);
                response.put('message', isUpdateMode ? 'Passager modifié avec succès.' : 'Passager ajouté avec succès.');
                response.put('participantId', participant.Id);
                return response;

            } catch (Exception e) {
                response.put('success', false);
                response.put('message', e.getMessage());
                return response;
            }
        }
            
        

            @AuraEnabled
            public static Map<String, Object> deletePassager(Id participantId) {
                Map<String, Object> response = new Map<String, Object>();
                if (participantId == null) {
                    response.put('success', false);
                    response.put('message', 'L\'identifiant du participant est requis.');
                    return response;
                }
                try {
                    DM005_ClaimParticipant.deleteById(participantId);
                    response.put('success', true);
                    response.put('message', 'Passager supprimé avec succès.');
                    return response;
                } catch (Exception e) {
                    response.put('success', false);
                    response.put('message', e.getMessage());
                    return response;
                }
            }

        }