force-app/main/default/objects/Account/fields/CIN__c.field-meta.xml
<CustomField>
    <fullName>CIN__c</fullName>
    <label>CIN</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Passager.recordType-meta.xml
<RecordType>
    <fullName>Passager</fullName>
    <active>true</active>
    <label>Passager</label>
</RecordType>

force-app/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Missions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <label>Commentaire</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Police__c.field-meta.xml
<CustomField>
    <fullName>Police__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Police</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipLabel>Déclarations</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Déclarations</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseCoverage__c/CaseCoverage__c.object-meta.xml
<CustomObject>
    <label>Case Coverage</label>
    <nameField>
        <label>Case Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseCoverage__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Coverages</relationshipLabel>
    <relationshipName>CaseCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseCoverage__c/fields/CodeGarantie__c.field-meta.xml
<CustomField>
    <fullName>CodeGarantie__c</fullName>
    <label>Code Garantie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <label>Commentaire</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/PolicyNumber__c.field-meta.xml
<CustomField>
    <fullName>PolicyNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Number</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <formula>HYPERLINK(
    Vehicule__c,
    Vehicule__r.RegistrationNumber__c,
    &quot;_blank&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro d’immatriculation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Réouvert</fullName>
            </value>
            <value>
                <fullName>Classé sans suite</fullName>
            </value>
            <value>
                <fullName>Sinistre clos, soldé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimCoverage__c/ClaimCoverage__c.object-meta.xml
<CustomObject>
    <label>Claim Coverage</label>
    <nameField>
        <label>Claim Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimCoverage__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Coverages</relationshipLabel>
    <relationshipName>ClaimCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/ClaimParticipant__c.object-meta.xml
<CustomObject>
    <label>Claim Participant</label>
    <nameField>
        <label>Claim Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimParticipant__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>ClaimParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Passager__c.field-meta.xml
<CustomField>
    <fullName>Passager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant de l&apos;accident</label>
    <referenceTo>Passager__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passager assuré</fullName>
            </value>
            <value>
                <fullName>Passager adverse</fullName>
            </value>
            <value>
                <fullName>Autres partie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Participants de l&apos;accident</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage__c/InsurancePolicyCoverage__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy Coverage</label>
    <nameField>
        <displayFormat>COV-{00000}</displayFormat>
        <label>Insurance Policy Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Policy Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/CodeGarantie__c.field-meta.xml
<CustomField>
    <fullName>CodeGarantie__c</fullName>
    <label>Code de la garantie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/GarantieUsed__c.field-meta.xml
<CustomField>
    <fullName>GarantieUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Garantie touchée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>InsurancePolicy__c</fullName>
    <label>Insurance Policy</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>InsurancePolicyCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/NomDeLaGarantie__c.field-meta.xml
<CustomField>
    <fullName>NomDeLaGarantie__c</fullName>
    <label>Nom de la garantie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/TypeGarantie__c.field-meta.xml
<CustomField>
    <fullName>TypeGarantie__c</fullName>
    <label>Type de la garantie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Materielle</fullName>
                <label>Matérielle</label>
            </value>
            <value>
                <fullName>Corporelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestApproval__c/RequestApproval__c.object-meta.xml
<CustomObject>
    <label>Demande d&apos;approbation</label>
    <nameField>
        <displayFormat>DA-{0000}</displayFormat>
        <label>RequestApproval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RequestApprovals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestApproval__c/fields/Commentaire__c.field-meta.xml
<CustomField>
    <fullName>Commentaire__c</fullName>
    <label>Commentaire</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RequestApproval__c/fields/NextApprover__c.field-meta.xml
<CustomField>
    <fullName>NextApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NextApprover</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestApprovals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestApproval__c/fields/Sinistre__c.field-meta.xml
<CustomField>
    <fullName>Sinistre__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>RequestApprovals</relationshipLabel>
    <relationshipName>RequestApprovals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RequestApproval__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Créée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>En attente d&apos;approbation</fullName>
            </value>
            <value>
                <fullName>Rejetée</fullName>
            </value>
            <value>
                <fullName>Approuvée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestApproval__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestApprovals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestApproval__c/fields/TypeApprobation__c.field-meta.xml
<CustomField>
    <fullName>TypeApprobation__c</fullName>
    <label>Type d&apos;approbation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flag du sinistre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicule__c/Vehicule__c.object-meta.xml
<CustomObject>
    <label>Véhicule</label>
    <nameField>
        <displayFormat>Véc-{00000}</displayFormat>
        <label>Numéro de véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Véhicules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/fields/AttestationNumber__c.field-meta.xml
<CustomField>
    <fullName>AttestationNumber__c</fullName>
    <label>Numéro d&apos;attestation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/ChassisNumber__c.field-meta.xml
<CustomField>
    <fullName>ChassisNumber__c</fullName>
    <label>N° Chassis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/DateOfFirstRegistration__c.field-meta.xml
<CustomField>
    <fullName>DateOfFirstRegistration__c</fullName>
    <label>Date de mise en circulation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>InsurancePolicy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Police d&apos;assurance</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipLabel>Véhicules</relationshipLabel>
    <relationshipName>vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <label>Numéro d&apos;immatriculation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DA_TestDataFactory.cls
@isTest
public class DA_TestDataFactory {

    private static Integer counter = 0;

    private static String uniqueSuffix() {
        counter++;
        return String.valueOf(System.currentTimeMillis()) + '_' + counter;
    }

    public static Id getStandardUserProfileId() {
        return [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id;
    }

    public static User createTestUser(String alias, String lastName, Map<String, Object> params) {
        String suffix = uniqueSuffix();
        User u = new User(
            Alias             = alias.left(8),
            Email             = 'u' + suffix + '@test.example.com',
            EmailEncodingKey  = 'UTF-8',
            LastName          = lastName,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey      = 'en_US',
            TimeZoneSidKey    = 'America/Los_Angeles',
            Username          = 'u' + suffix + '@test.assurance.factory',
            ProfileId         = getStandardUserProfileId()
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                u.put(fieldName, params.get(fieldName));
            }
        }
        return u;
    }

    public static Account createTestAccount(Map<String, Object> params) {
        Account acc = new Account(
            Name = 'TestAccount_' + uniqueSuffix()
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                acc.put(fieldName, params.get(fieldName));
            }
        }
        return acc;
    }

    public static InsurancePolicy__c createTestPolicy(Id accountId, Map<String, Object> params) {
        String suffix = uniqueSuffix();
        InsurancePolicy__c pol = new InsurancePolicy__c(
            Name               = 'POL_' + suffix,
            PolicyNumber__c    = 'POL_' + suffix,
            PolicyCategory__c  = 'Individuelle',
            DateEffet__c       = Date.today(),
            DateExpiration__c  = Date.today().addYears(1),
            Canal__c           = 'Agent',
            Status__c          = 'Initiale',
            SituationPolice__c = 'En cours',
            AccountName__c     = accountId
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                pol.put(fieldName, params.get(fieldName));
            }
        }
        return pol;
    }

    public static Vehicule__c createTestVehicle(Id policyId, Map<String, Object> params) {
        String suffix = uniqueSuffix();
        Vehicule__c veh = new Vehicule__c(
            RegistrationNumber__c      = 'AA' + suffix.right(6),
            ChassisNumber__c           = 'CH' + suffix,
            AttestationNumber__c       = 'AT' + suffix,
            DateOfFirstRegistration__c = Date.today().addYears(-2),
            InsurancePolicy__c         = policyId
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                veh.put(fieldName, params.get(fieldName));
            }
        }
        return veh;
    }

    public static Case createTestCase(Id accountId, Id policyId, String subject, Map<String, Object> params) {
        Case c = new Case(
            Subject     = subject,
            Origin      = 'Web',
            AccountId   = accountId,
            Police__c   = policyId
           
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                c.put(fieldName, params.get(fieldName));
            }
        }
        return c;
    }

    public static Claim__c createTestClaim(Id caseId, Map<String, Object> params) {
        Claim__c claim = new Claim__c(
            Case__c     = caseId
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                claim.put(fieldName, params.get(fieldName));
            }
        }
        return claim;
    }

    public static Passager__c createTestPassenger(Id caseId, Id accountId, Id vehiculeId, Map<String, Object> params) {
        Passager__c p = new Passager__c(
            Case__c     = caseId,
            Compte__c   = accountId,
            Vehicule__c = vehiculeId,
            Roles__c    = 'Passager assuré',
            CIN__c      = 'CIN' + uniqueSuffix()
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                p.put(fieldName, params.get(fieldName));
            }
        }
        return p;
    }

    public static RequestApproval__c createTestRequestApproval(Id claimId, Id submitterId, Id approverId, Map<String, Object> params) {
        RequestApproval__c r = new RequestApproval__c(
            Status__c          = 'En attente d\'approbation',
            TypeApprobation__c = 'Flag du sinistre',
            Commentaire__c     = 'Test',
            Sinistre__c        = claimId,
            Submitter__c       = submitterId,
            NextApprover__c    = approverId
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                r.put(fieldName, params.get(fieldName));
            }
        }
        return r;
    }

    public static InsurancePolicyCoverage__c createTestInsurancePolicyCoverage(Id policyId, Map<String, Object> params) {
        String suffix = uniqueSuffix();
        InsurancePolicyCoverage__c cov = new InsurancePolicyCoverage__c(
            InsurancePolicy__c = policyId,
            CodeGarantie__c    = 'GAR_' + suffix,
            NomDeLaGarantie__c = 'Test Garantie ' + suffix,
            TypeGarantie__c    = 'Matérielle',
            GarantieUsed__c    = false
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                cov.put(fieldName, params.get(fieldName));
            }
        }
        return cov;
    }

    public static ClaimCoverage__c createTestClaimCoverage(Id claimId, Id policyCoverageId, Map<String, Object> params) {
        ClaimCoverage__c cov = new ClaimCoverage__c(
            Claim__c                     = claimId,
            Insurance_Policy_Coverage__c = policyCoverageId,
            CodeGarantie__c              = 'GAR_TEST',
            NatureEvaluation__c          = 'Indemnité principale',
            EvaluationActuelle__c        = 1000,
            TypeEvaluation__c            = 'Evaluation Matérielle'
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                cov.put(fieldName, params.get(fieldName));
            }
        }
        return cov;
    }

    public static CaseCoverage__c createTestCaseCoverage(Id caseId, Id policyCoverageId, Map<String, Object> params) {
        CaseCoverage__c cov = new CaseCoverage__c(
            Case__c                      = caseId,
            Insurance_Policy_Coverage__c = policyCoverageId,
            CodeGarantie__c              = 'GAR_TEST',
            NatureEvaluation__c          = 'Matériel',
            EvaluationActuelle__c        = 1000,
            TypeEvaluation__c            = 'Provision'
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                cov.put(fieldName, params.get(fieldName));
            }
        }
        return cov;
    }

    public static ClaimParticipant__c createTestClaimParticipant(Id claimId, Id accountId, Map<String, Object> params) {
        ClaimParticipant__c p = new ClaimParticipant__c(
            Claim__c              = claimId,
            ParticipantAccount__c = accountId,
            Roles__c              = 'Passager assuré',
            Civilite__c           = 'Mr',
            StateOfPerson__c      = 'Indemne',
            isDriver__c           = false
        );
        if (params != null) {
            for (String fieldName : params.keySet()) {
                p.put(fieldName, params.get(fieldName));
            }
        }
        return p;
    }
}