force-app/main/default/objects/Account/fields/codeTier__c.field-meta.xml
<CustomField>
    <fullName>codeTier__c</fullName>
    <label>Code prestataire</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Conventionne__c.field-meta.xml
<CustomField>
    <fullName>Conventionne__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique si le prestataire (garagiste/concessionnaire) est conventionné avec la compagnie.</description>
    <label>Conventionné</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Pays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Pays__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ville</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prestataire.recordType-meta.xml
<RecordType>
    <fullName>Prestataire</fullName>
    <active>true</active>
    <label>Prestataire</label>
</RecordType>

force-app/main/default/objects/Case/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Missions</relationshipLabel>
    <relationshipName>Missions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateOfDeclarationCreation__c.field-meta.xml
<CustomField>
    <fullName>DateOfDeclarationCreation__c</fullName>
    <label>Date création déclaration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DateOfOccurrence__c.field-meta.xml
<CustomField>
    <fullName>DateOfOccurrence__c</fullName>
    <label>Date de survenance</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Requete.recordType-meta.xml
<RecordType>
    <fullName>Requete</fullName>
    <active>true</active>
    <businessProcess>Record Process</businessProcess>
    <label>requête</label>
</RecordType>

force-app/main/default/objects/Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/DateOfOccurrence__c.field-meta.xml
<CustomField>
    <fullName>DateOfOccurrence__c</fullName>
    <formula>Case__r.DateOfOccurrence__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de survenance</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Correction_Devis__c/Correction_Devis__c.object-meta.xml
<CustomObject>
    <description>Ligne de correction de devis liée à une instruction PEC (bloc « Données devis corrigé »).</description>
    <label>Correction Devis</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>N° Correction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corrections Devis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Correction_Devis__c/fields/DateStatut__c.field-meta.xml
<CustomField>
    <fullName>DateStatut__c</fullName>
    <description>Date système récupérée automatiquement au changement du statut correction (RG8).</description>
    <label>Date statut</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Correction_Devis__c/fields/Instruction__c.field-meta.xml
<CustomField>
    <fullName>Instruction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Instruction PEC à laquelle la ligne de correction de devis est rattachée.</description>
    <label>Instruction</label>
    <referenceTo>Instruction__c</referenceTo>
    <relationshipLabel>Corrections Devis</relationshipLabel>
    <relationshipName>Corrections_Devis</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correction_Devis__c/fields/MontantDevisCorrige__c.field-meta.xml
<CustomField>
    <fullName>MontantDevisCorrige__c</fullName>
    <label>Montant devis corrigé</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Correction_Devis__c/fields/OrigineCorrection__c.field-meta.xml
<CustomField>
    <fullName>OrigineCorrection__c</fullName>
    <label>Origine correction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revue en interne</fullName>
            </value>
            <value>
                <fullName>Revue d&apos;expert sur document</fullName>
            </value>
            <value>
                <fullName>Revue d&apos;expert suite à expertise véhicule</fullName>
            </value>
            <value>
                <fullName>Contre-proposition garagiste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Correction_Devis__c/fields/Reparateur__c.field-meta.xml
<CustomField>
    <fullName>Reparateur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Réparateur (Garagiste/Concessionnaire) retenu pour la ligne de correction.</description>
    <label>Réparateur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Corrections Devis (Réparateur)</relationshipLabel>
    <relationshipName>Corrections_Devis_Reparateur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Correction_Devis__c/fields/StatutCorrection__c.field-meta.xml
<CustomField>
    <fullName>StatutCorrection__c</fullName>
    <label>Statut correction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soumise</fullName>
                <default>true</default>
                <label>Soumise</label>
            </value>
            <value>
                <fullName>Confirmée</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Abandonnée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/Instruction__c.object-meta.xml
<CustomObject>
    <label>Instruction</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>N° Instruction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Instruction__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Instructions</relationshipLabel>
    <relationshipName>Instructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/CommentaireDevisInitial__c.field-meta.xml
<CustomField>
    <fullName>CommentaireDevisInitial__c</fullName>
    <label>Commentaire (devis initial)</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/CommentairePEC__c.field-meta.xml
<CustomField>
    <fullName>CommentairePEC__c</fullName>
    <label>Commentaire (prise en charge)</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/DateEnvoiPEC__c.field-meta.xml
<CustomField>
    <fullName>DateEnvoiPEC__c</fullName>
    <label>Date d&apos;envoi de la PEC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/DateReceptionDevisInitial__c.field-meta.xml
<CustomField>
    <fullName>DateReceptionDevisInitial__c</fullName>
    <label>Date réception devis initial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/EtapePEC__c.field-meta.xml
<CustomField>
    <fullName>EtapePEC__c</fullName>
    <description>Etape courante du workflow PEC : pilote les droits de saisie sur l&apos;onglet Détails PEC.</description>
    <label>Etape PEC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Etude de document</fullName>
                <default>true</default>
                <label>Etude de document</label>
            </value>
            <value>
                <fullName>Expertise</fullName>
            </value>
            <value>
                <fullName>Correction devis</fullName>
            </value>
            <value>
                <fullName>Etablissement PEC</fullName>
            </value>
            <value>
                <fullName>Réparation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/FranchiseMax__c.field-meta.xml
<CustomField>
    <fullName>FranchiseMax__c</fullName>
    <label>Franchise Max</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/FranchiseMin__c.field-meta.xml
<CustomField>
    <fullName>FranchiseMin__c</fullName>
    <label>Franchise Min</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/FranchisePourcentage__c.field-meta.xml
<CustomField>
    <fullName>FranchisePourcentage__c</fullName>
    <label>Franchise (en %)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/IdentifiantFiscal__c.field-meta.xml
<CustomField>
    <fullName>IdentifiantFiscal__c</fullName>
    <label>Identifiant fiscal</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/MontantAccordePEC__c.field-meta.xml
<CustomField>
    <fullName>MontantAccordePEC__c</fullName>
    <label>Montant accordée PEC</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/MontantApprecie__c.field-meta.xml
<CustomField>
    <fullName>MontantApprecie__c</fullName>
    <label>Montant apprécié</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/MontantDevisInitial__c.field-meta.xml
<CustomField>
    <fullName>MontantDevisInitial__c</fullName>
    <label>Montant devis initial</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/NecessiteExpertise__c.field-meta.xml
<CustomField>
    <fullName>NecessiteExpertise__c</fullName>
    <label>Nécessite une expertise ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/NomReparateur__c.field-meta.xml
<CustomField>
    <fullName>NomReparateur__c</fullName>
    <label>Nom réparateur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/NouveauReparateurNonConventionne__c.field-meta.xml
<CustomField>
    <fullName>NouveauReparateurNonConventionne__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Nouveau réparateur « non conventionné »</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/ObligationRapportExpertise__c.field-meta.xml
<CustomField>
    <fullName>ObligationRapportExpertise__c</fullName>
    <description>Obligation Rapport d&apos;expertise post travaux</description>
    <label>Obligation Rapport expertise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/OrigineDevis__c.field-meta.xml
<CustomField>
    <fullName>OrigineDevis__c</fullName>
    <label>Origine devis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garage conventionné</fullName>
            </value>
            <value>
                <fullName>Garage non conventionné</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/PaiementFranchise__c.field-meta.xml
<CustomField>
    <fullName>PaiementFranchise__c</fullName>
    <label>Paiement de la franchise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A la compagnie</fullName>
            </value>
            <value>
                <fullName>Au garagiste</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/Reparateur__c.field-meta.xml
<CustomField>
    <fullName>Reparateur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Réparateur (Garagiste/Concessionnaire) retenu pour le devis initial.</description>
    <label>Réparateur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Instructions (Réparateur)</relationshipLabel>
    <relationshipName>Instructions_Reparateur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DA_lwc031_DetailsPECController.cls
// ═══════════════════════════════════════════════════════════════
// DA_lwc031_DetailsPECController — Onglet [Détails PEC]
// Workflow PEC : Etude de document → Expertise → Correction devis
//                → Etablissement PEC → Réparation
// ═══════════════════════════════════════════════════════════════
public with sharing class DA_lwc031_DetailsPECController {

    private static final List<String> ETAPES = new List<String>{
        'Etude de document',
        'Expertise',
        'Correction devis',
        'Etablissement PEC',
        'Réparation'
    };

    private static final String FIELDS_INSTRUCTION =
        'Id, Name, Claim__c, EtapePEC__c, ' +
        'MontantDevisInitial__c, DateReceptionDevisInitial__c, OrigineDevis__c, ' +
        'Reparateur__c, Reparateur__r.Name, NouveauReparateurNonConventionne__c, ' +
        'NomReparateur__c, IdentifiantFiscal__c, ' +
        'MontantApprecie__c, NecessiteExpertise__c, CommentaireDevisInitial__c, ' +
        'MontantAccordePEC__c, FranchisePourcentage__c, FranchiseMin__c, FranchiseMax__c, ' +
        'PaiementFranchise__c, ObligationRapportExpertise__c, CommentairePEC__c, DateEnvoiPEC__c';

    // ── Wrapper ──────────────────────────────────────────────────────────────
    public class DetailsPECWrapper {
        @AuraEnabled public Instruction__c instruction;
        @AuraEnabled public List<Correction_Devis__c> corrections;
        @AuraEnabled public Date dateSinistre;
        @AuraEnabled public Date dateDeclaration;
    }

    // ── Lecture ──────────────────────────────────────────────────────────────
    @AuraEnabled(cacheable=true)
    public static DetailsPECWrapper getDetailsPEC(Id instructionId) {
        if (instructionId == null) {
            return null; // le wire se déclenche avant que recordId soit disponible
        }

        DetailsPECWrapper wrapper = new DetailsPECWrapper();
        wrapper.instruction = (Instruction__c) DA_Utility.getById(
            FIELDS_INSTRUCTION, 'Instruction__c', instructionId
        );
        if (wrapper.instruction == null) {
            throw new AuraHandledException('Instruction introuvable.');
        }

        wrapper.corrections = getCorrections(instructionId);

        // RG1 (devis initial) : dates de référence du sinistre / de la déclaration
        if (wrapper.instruction.Claim__c != null) {
            List<Claim__c> claims = [
                SELECT Id, DateOfOccurrence__c, Case__r.DateOfDeclarationCreation__c
                FROM Claim__c
                WHERE Id = :wrapper.instruction.Claim__c
                LIMIT 1
            ];
            if (!claims.isEmpty()) {
                if (claims[0].DateOfOccurrence__c != null) {
                    wrapper.dateSinistre = claims[0].DateOfOccurrence__c.date();
                }
                wrapper.dateDeclaration = claims[0].Case__r != null
                    ? claims[0].Case__r.DateOfDeclarationCreation__c
                    : null;
            }
        }
        return wrapper;
    }

    private static List<Correction_Devis__c> getCorrections(Id instructionId) {
        return [
            SELECT Id, Name, MontantDevisCorrige__c, OrigineCorrection__c,
                   Reparateur__c, Reparateur__r.Name, StatutCorrection__c, DateStatut__c,
                   CreatedDate
            FROM Correction_Devis__c
            WHERE Instruction__c = :instructionId
            ORDER BY CreatedDate ASC
        ];
    }

    /**
     * RG2 / RG3 : liste des garagistes filtrée sur le pays de l'utilisateur
     * connecté et sur le type conventionné / non conventionné.
     */
    @AuraEnabled
    public static List<Account> getGaragistes(Boolean conventionne) {
        Id rtId = DA_Utility.getRecordTypeId('Account', 'Prestataire');

        User currentUser = [SELECT Country FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        String pays = currentUser.Country;

        String query = 'SELECT Id, Name, codeTier__c, Ville__c, Pays__c, Conventionne__c '
            + 'FROM Account '
            + 'WHERE RecordTypeId = :rtId '
            + 'AND TypeDePrestataire__c = \'Garagiste\' '
            + 'AND Conventionne__c = :conventionne ';
        if (String.isNotBlank(pays)) {
            query += 'AND Pays__c = :pays ';
        }
        query += 'ORDER BY Name LIMIT 200';

        return Database.query(query);
    }

    // ── US1 : Etape 1 — Etude de document (RG5) ──────────────────────────────
    @AuraEnabled
    public static void saveDevisInitial(Id instructionId, String payload) {
        Map<String, Object> data = parse(payload);
        Instruction__c instr = new Instruction__c(Id = instructionId);

        instr.MontantDevisInitial__c       = toDecimal(data.get('montantDevisInitial'));
        instr.DateReceptionDevisInitial__c = toDate(data.get('dateReceptionDevisInitial'));
        instr.OrigineDevis__c              = (String) data.get('origineDevis');
        instr.NouveauReparateurNonConventionne__c = data.get('nouveauReparateur') == true;
        instr.Reparateur__c                = toId(data.get('reparateurId'));
        instr.NomReparateur__c             = (String) data.get('nomReparateur');
        instr.IdentifiantFiscal__c         = (String) data.get('identifiantFiscal');
        instr.MontantApprecie__c           = toDecimal(data.get('montantApprecie'));
        instr.NecessiteExpertise__c        = (String) data.get('necessiteExpertise');
        instr.CommentaireDevisInitial__c   = (String) data.get('commentaire');

        // Contrôles champs obligatoires (RG5)
        if (instr.MontantDevisInitial__c == null)       throw new AuraHandledException('Le champ « Montant devis initial » est obligatoire.');
        if (instr.DateReceptionDevisInitial__c == null) throw new AuraHandledException('Le champ « Date réception devis initial » est obligatoire.');
        if (String.isBlank(instr.OrigineDevis__c))      throw new AuraHandledException('Le champ « Origine devis » est obligatoire.');
        if (String.isBlank(instr.NecessiteExpertise__c)) throw new AuraHandledException('Le champ « Nécessite une expertise ? » est obligatoire.');
        if (!instr.NouveauReparateurNonConventionne__c && instr.Reparateur__c == null) {
            throw new AuraHandledException('Veuillez sélectionner un réparateur ou cocher « Nouveau réparateur non conventionné ».');
        }
        if (instr.NouveauReparateurNonConventionne__c && String.isBlank(instr.NomReparateur__c)) {
            throw new AuraHandledException('Le champ « Nom réparateur » est obligatoire.');
        }

        // RG1 : la date de réception ne peut pas être antérieure à la date
        // sinistre ni à la date de déclaration
        DetailsPECWrapper ctx = getDetailsPEC(instructionId);
        if (ctx.dateSinistre != null && instr.DateReceptionDevisInitial__c < ctx.dateSinistre) {
            throw new AuraHandledException('La date de réception du devis ne peut pas être antérieure à la date du sinistre.');
        }
        if (ctx.dateDeclaration != null && instr.DateReceptionDevisInitial__c < ctx.dateDeclaration) {
            throw new AuraHandledException('La date de réception du devis ne peut pas être antérieure à la date de déclaration.');
        }

        update instr;
    }

    // ── US2 : Etape 2 — Expertise ────────────────────────────────────────────
    @AuraEnabled
    public static void saveExpertise(Id instructionId, String payload) {
        Map<String, Object> data = parse(payload);
        update new Instruction__c(
            Id                         = instructionId,
            MontantApprecie__c         = toDecimal(data.get('montantApprecie')),
            CommentaireDevisInitial__c = (String) data.get('commentaire')
        );
    }

    // ── US3 : Etape 3 — Correction devis (RG9) ───────────────────────────────
    @AuraEnabled
    public static void saveCorrection(Id instructionId, String payload) {
        Map<String, Object> data = parse(payload);
        Id correctionId = toId(data.get('id'));
        String statut   = (String) data.get('statutCorrection');

        if (String.isBlank(statut)) {
            throw new AuraHandledException('Le champ « Statut correction » est obligatoire.');
        }

        if (correctionId == null) {
            // Nouvelle ligne : tous les champs obligatoires
            Decimal montant     = toDecimal(data.get('montantDevisCorrige'));
            String origine      = (String) data.get('origineCorrection');
            Id reparateurId     = toId(data.get('reparateurId'));

            if (montant == null)              throw new AuraHandledException('Le champ « Montant devis corrigé » est obligatoire.');
            if (String.isBlank(origine))      throw new AuraHandledException('Le champ « Origine correction » est obligatoire.');
            if (reparateurId == null)         throw new AuraHandledException('Le champ « Réparateur » est obligatoire.');

            insert new Correction_Devis__c(
                Instruction__c         = instructionId,
                MontantDevisCorrige__c = montant,
                OrigineCorrection__c   = origine,
                Reparateur__c          = reparateurId,
                StatutCorrection__c    = statut,
                DateStatut__c          = Date.today()   // RG8 : date système
            );
        } else {
            // RG4/RG5/RG6 : seuls le statut (RG7) et la date statut évoluent
            Correction_Devis__c existing = [
                SELECT Id, StatutCorrection__c FROM Correction_Devis__c
                WHERE Id = :correctionId LIMIT 1
            ];
            existing.StatutCorrection__c = statut;
            existing.DateStatut__c       = Date.today(); // RG8
            update existing;
        }
    }

    // ── US4 : Etape 4 — Etablissement PEC (RG4) ──────────────────────────────
    @AuraEnabled
    public static void savePriseEnCharge(Id instructionId, String payload) {
        Map<String, Object> data = parse(payload);
        Instruction__c instr = new Instruction__c(Id = instructionId);

        instr.MontantAccordePEC__c          = toDecimal(data.get('montantAccordePEC'));
        instr.FranchisePourcentage__c       = toDecimal(data.get('franchisePourcentage'));
        instr.FranchiseMin__c               = toDecimal(data.get('franchiseMin'));
        instr.FranchiseMax__c               = toDecimal(data.get('franchiseMax'));
        instr.PaiementFranchise__c          = (String) data.get('paiementFranchise');
        instr.ObligationRapportExpertise__c = (String) data.get('obligationRapportExpertise');
        instr.CommentairePEC__c             = (String) data.get('commentaire');
        instr.DateEnvoiPEC__c               = toDate(data.get('dateEnvoiPEC'));

        if (instr.MontantAccordePEC__c == null)              throw new AuraHandledException('Le champ « Montant accordée PEC » est obligatoire.');
        if (instr.FranchisePourcentage__c == null)           throw new AuraHandledException('Le champ « Franchise (en %) » est obligatoire.');
        if (instr.FranchisePourcentage__c > 100)             throw new AuraHandledException('La franchise ne peut pas dépasser 100 %.'); // RG2
        if (instr.FranchiseMin__c == null)                   throw new AuraHandledException('Le champ « Franchise Min » est obligatoire.');
        if (instr.FranchiseMax__c == null)                   throw new AuraHandledException('Le champ « Franchise MAX » est obligatoire.');
        if (String.isBlank(instr.PaiementFranchise__c))      throw new AuraHandledException('Le champ « Paiement de la franchise » est obligatoire.');
        if (String.isBlank(instr.ObligationRapportExpertise__c)) throw new AuraHandledException('Le champ « Obligation Rapport d\'expertise post travaux » est obligatoire.');
        if (instr.DateEnvoiPEC__c == null)                   throw new AuraHandledException('Le champ « Date d\'envoi de la PEC » est obligatoire.');

        update instr;
    }

    /**
     * RG4 (devis initial) : création d'une requête « Création prestataire »
     * affectée au gestionnaire « Admin fonctionnel » (case à cocher sur
     * l'utilisateur) du pays de l'utilisateur, avec notification cloche
     * pointant vers l'instruction.
     */
    @AuraEnabled
    public static Id creerRequetePrestataire(Id instructionId, String nomReparateur, String identifiantFiscal) {
        if (String.isBlank(nomReparateur)) {
            throw new AuraHandledException('Le champ « Nom réparateur » est obligatoire.');
        }

        Instruction__c instr = [SELECT Id, Name FROM Instruction__c WHERE Id = :instructionId LIMIT 1];

        User currentUser = [SELECT Country FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        Id ownerId = findAdminFonctionnel(currentUser.Country);

        Case requete = new Case(
            RecordTypeId         = DM_Case.getRequeteRecordTypeId(),
            SourceRequete__c     = 'Instruction',
            CategorieRequete__c  = 'Création prestataire',
            TypeRequete__c       = 'Création prestataire',
            Priority             = 'Haute',
            Status               = 'Initiale',
            OwnerId              = ownerId,
            Delais_Traitement__c = 2,   // 2 JH
            Subject              = 'Création prestataire — ' + nomReparateur,
            Description          = 'Demande de création d\'un nouveau réparateur non conventionné.\n'
                                 + 'Nom réparateur : ' + nomReparateur + '\n'
                                 + 'Identifiant fiscal : ' + (String.isBlank(identifiantFiscal) ? '-' : identifiantFiscal) + '\n'
                                 + 'Réf source (instruction) : ' + instr.Id + ' (' + instr.Name + ')'
        );
        insert requete;

        sendNotificationCreationPrestataire(ownerId, instr, nomReparateur);
        return requete.Id;
    }

    // ── Avancement du workflow ───────────────────────────────────────────────
    @AuraEnabled
    public static String passerEtapeSuivante(Id instructionId) {
        Instruction__c instr = [SELECT Id, EtapePEC__c FROM Instruction__c WHERE Id = :instructionId LIMIT 1];

        String current = String.isBlank(instr.EtapePEC__c) ? ETAPES[0] : instr.EtapePEC__c;
        Integer idx = ETAPES.indexOf(current);
        if (idx < 0) idx = 0;
        if (idx >= ETAPES.size() - 1) {
            throw new AuraHandledException('L\'instruction est déjà à la dernière étape du workflow.');
        }

        instr.EtapePEC__c = ETAPES[idx + 1];
        update instr;
        return instr.EtapePEC__c;
    }

    /**
     * Navigation directe vers une étape via le stepper (avant / arrière).
     */
    @AuraEnabled
    public static String setEtape(Id instructionId, String etape) {
        if (!ETAPES.contains(etape)) {
            throw new AuraHandledException('Étape inconnue : ' + etape);
        }
        update new Instruction__c(Id = instructionId, EtapePEC__c = etape);
        return etape;
    }

    // ── Privé ────────────────────────────────────────────────────────────────
    // Le gestionnaire « Admin fonctionnel » est désigné via la case à cocher
    // AdminFonctionnel__c sur l'utilisateur (et non plus via un profil).
    private static Id findAdminFonctionnel(String pays) {
        List<User> admins;
        if (String.isNotBlank(pays)) {
            admins = [
                SELECT Id FROM User
                WHERE AdminFonctionnel__c = true AND IsActive = true AND Country = :pays
                LIMIT 1
            ];
            if (!admins.isEmpty()) return admins[0].Id;
        }
        admins = [
            SELECT Id FROM User
            WHERE AdminFonctionnel__c = true AND IsActive = true
            LIMIT 1
        ];
        return admins.isEmpty() ? UserInfo.getUserId() : admins[0].Id;
    }

    private static void sendNotificationCreationPrestataire(Id ownerId, Instruction__c instr, String nomReparateur) {
        List<CustomNotificationType> notifTypes = [
            SELECT Id FROM CustomNotificationType
            WHERE DeveloperName = 'Flag_Sinistre_Notification'
            LIMIT 1
        ];
        if (notifTypes.isEmpty()) return;

        try {
            Messaging.CustomNotification notif = new Messaging.CustomNotification();
            notif.setNotificationTypeId(notifTypes[0].Id);
            notif.setTitle('Création prestataire — ' + nomReparateur);
            notif.setBody('Une requête de création du prestataire « ' + nomReparateur
                + ' » a été générée depuis l\'instruction ' + instr.Name + '.');
            notif.setTargetId(instr.Id); // lien vers l'instruction d'origine
            notif.send(new Set<String>{ String.valueOf(ownerId) });
        } catch (Exception e) {
            System.debug('Erreur envoi notification: ' + e.getMessage());
        }
    }

    private static Map<String, Object> parse(String payload) {
        if (String.isBlank(payload)) {
            throw new AuraHandledException('Aucune donnée à enregistrer.');
        }
        return (Map<String, Object>) JSON.deserializeUntyped(payload);
    }

    private static Decimal toDecimal(Object value) {
        if (value == null) return null;
        if (value instanceof Decimal) return (Decimal) value;
        String s = String.valueOf(value);
        return String.isBlank(s) ? null : Decimal.valueOf(s);
    }

    private static Date toDate(Object value) {
        if (value == null) return null;
        String s = String.valueOf(value);
        return String.isBlank(s) ? null : Date.valueOf(s);
    }

    private static Id toId(Object value) {
        if (value == null) return null;
        String s = String.valueOf(value);
        return String.isBlank(s) ? null : (Id) s;
    }
}