force-app/main/default/objects/Account/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Féminin</fullName>
            </value>
            <value>
                <fullName>Masculin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <formula>HYPERLINK(
    Vehicule__c,
    Vehicule__r.RegistrationNumber__c,
    &quot;_blank&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro d’immatriculation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimCoverage__c/ClaimCoverage__c.object-meta.xml
<CustomObject>
    <label>Claim Coverage</label>
    <nameField>
        <label>Claim Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimCoverage__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Coverages</relationshipLabel>
    <relationshipName>ClaimCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimCoverage__c/fields/Insurance_Policy_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Policy_Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Policy Coverage</label>
    <referenceTo>InsurancePolicyCoverage__c</referenceTo>
    <relationshipLabel>Claim Coverages</relationshipLabel>
    <relationshipName>Claim_Coverages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/ClaimParticipant__c.object-meta.xml
<CustomObject>
    <label>Claim Participant</label>
    <nameField>
        <label>Claim Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimParticipant__c/fields/BirthDay__c.field-meta.xml
<CustomField>
    <fullName>BirthDay__c</fullName>
    <label>Date de Naissance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>ClaimParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/isDriver__c.field-meta.xml
<CustomField>
    <fullName>isDriver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Participant est conducteur ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ParticipantAccount__c.field-meta.xml
<CustomField>
    <fullName>ParticipantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nom et Prénom</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passager assuré</fullName>
            </value>
            <value>
                <fullName>Passager adverse</fullName>
            </value>
            <value>
                <fullName>Autres partie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Féminin</fullName>
            </value>
            <value>
                <fullName>Masculin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/StateOfPerson__c.field-meta.xml
<CustomField>
    <fullName>StateOfPerson__c</fullName>
    <label>Etat du Participant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indemne</fullName>
            </value>
            <value>
                <fullName>Blessé</fullName>
            </value>
            <value>
                <fullName>Décédé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/TypeContact__c.field-meta.xml
<CustomField>
    <fullName>TypeContact__c</fullName>
    <label>Type de Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Téléphone</fullName>
            </value>
            <value>
                <fullName>Mail et Téléphone</fullName>
                <default>true</default>
                <label>Mail et Téléphone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Participants de l&apos;accident</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instruction__c/Instruction__c.object-meta.xml
<CustomObject>
    <label>Instruction</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>N° Instruction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Instruction__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Sinistre</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Instructions</relationshipLabel>
    <relationshipName>Instructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/InstructionType__c.field-meta.xml
<CustomField>
    <fullName>InstructionType__c</fullName>
    <label>Type d’instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PEC - Prise en charge</fullName>
            </value>
            <value>
                <fullName>Remboursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Instruction créé</fullName>
            </value>
            <value>
                <fullName>Instruction annulée</fullName>
            </value>
            <value>
                <fullName>Instruction terminée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/TypeDegat__c.field-meta.xml
<CustomField>
    <fullName>TypeDegat__c</fullName>
    <label>Type de dégât</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Matériel</fullName>
            </value>
            <value>
                <fullName>Corporel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Instructions</relationshipLabel>
    <relationshipName>Instructions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/Victimes__c.field-meta.xml
<CustomField>
    <fullName>Victimes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Victimes</label>
    <referenceTo>ClaimParticipant__c</referenceTo>
    <relationshipLabel>Instructions</relationshipLabel>
    <relationshipName>Instructions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/Vehicule__c.object-meta.xml
<CustomObject>
    <label>Véhicule</label>
    <nameField>
        <displayFormat>Véc-{00000}</displayFormat>
        <label>Numéro de véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Véhicules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/fields/AttestationNumber__c.field-meta.xml
<CustomField>
    <fullName>AttestationNumber__c</fullName>
    <label>Numéro d&apos;attestation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marque</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jaguar</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>FORD</fullName>
            </value>
            <value>
                <fullName>Fiat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/DateOfFirstRegistration__c.field-meta.xml
<CustomField>
    <fullName>DateOfFirstRegistration__c</fullName>
    <label>Date de mise en circulation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/Modele__c.field-meta.xml
<CustomField>
    <fullName>Modele__c</fullName>
    <label>Modèle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/ProprietaireDuVehicule__c.field-meta.xml
<CustomField>
    <fullName>ProprietaireDuVehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire du véhicule</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Véhicules (Propriétaire du véhicule)</relationshipLabel>
    <relationshipName>V_hicules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <label>Numéro d&apos;immatriculation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/fields/TypeVehicule__c.field-meta.xml
<CustomField>
    <fullName>TypeVehicule__c</fullName>
    <label>Type véhicule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Une voiture</fullName>
            </value>
            <value>
                <fullName>Un camion</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
            <value>
                <fullName>Autres cas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DM008_Instruction.cls
// ═══════════════════════════════════════════════════════════════
// DM008_Instruction — Data Manager (lecture uniquement)
// ═══════════════════════════════════════════════════════════════
public with sharing class DM008_Instruction {

    private static final String OBJECT_INSTRUCTION = 'Instruction__c';
    private static final String OBJECT_CLAIM       = 'Claim__c';
    private static final String OBJECT_VEHICULE    = 'Vehicule__c';
    private static final String OBJECT_PARTICIPANT = 'ClaimParticipant__c';
    private static final String OBJECT_COVERAGE    = 'ClaimCoverage__c';

    private static final String FIELDS_INSTRUCTION =
        'Id, Name, InstructionType__c, TypeDegat__c, Statut__c, ' +
        'Vehicule__c, Vehicule__r.Name, ' +
        'Victimes__c, Victimes__r.Name, ' +
        'Victimes__r.ParticipantAccount__c, Victimes__r.ParticipantAccount__r.Name, ' +
        'CreatedDate, RecordTypeId, RecordType.DeveloperName';

    private static final String FIELDS_VEHICULE =
        'Id, Name, RegistrationNumber__c, Brand__c, Modele__c, TypeVehicule__c, ' +
        'ProprietaireDuVehicule__c, ProprietaireDuVehicule__r.Name, ' +
        'AttestationNumber__c, DateOfFirstRegistration__c';

    private static final String FIELDS_PARTICIPANT =
        'Id, Name, ParticipantAccount__c, ParticipantAccount__r.Name, ' +
        'Roles__c, StateOfPerson__c, BirthDay__c, TypeContact__c, ' +
        'isDriver__c, Civilite__c, Sexe__c';

    private static final String FIELDS_COVERAGE =
        'Id, Name, CodeGarantie__c, Insurance_Policy_Coverage__c, Claim__c';

    /**
     * Récupère les instructions liées à un sinistre.
     */
    public static List<Instruction__c> getByClaimId(Id claimId) {
        if (claimId == null) return new List<Instruction__c>();
        String safeId    = String.escapeSingleQuotes(String.valueOf(claimId));
        String conditions = 'Claim__c = \'' + safeId + '\'';
        return (List<Instruction__c>) DA_Utility.query(
            FIELDS_INSTRUCTION, OBJECT_INSTRUCTION, conditions, 'CreatedDate DESC', null
        );
    }

    /**
     * Récupère une instruction par son Id (avec Claim__c).
     */
    public static Instruction__c getById(Id instructionId) {
        if (instructionId == null) return null;
        return (Instruction__c) DA_Utility.getById(
            'Id, Claim__c', OBJECT_INSTRUCTION, instructionId
        );
    }

    /**
     * Récupère le véhicule lié à un sinistre (via Claim__c.Vehicule__c).
     */
    public static List<Vehicule__c> getVehiculesByClaimId(Id claimId) {
        if (claimId == null) return new List<Vehicule__c>();
        Claim__c claim = (Claim__c) DA_Utility.getById('Id, Vehicule__c', OBJECT_CLAIM, claimId);
        if (claim == null || claim.Vehicule__c == null) {
            return new List<Vehicule__c>();
        }
        String safeVehId = String.escapeSingleQuotes(String.valueOf(claim.Vehicule__c));
        String conditions = 'Id = \'' + safeVehId + '\'';
        return (List<Vehicule__c>) DA_Utility.query(
            FIELDS_VEHICULE, OBJECT_VEHICULE, conditions, null, 1
        );
    }

    /**
     * Récupère les victimes / passagers liés à un sinistre.
     */
    public static List<ClaimParticipant__c> getVictimesByClaimId(Id claimId) {
        if (claimId == null) return new List<ClaimParticipant__c>();
        String safeId    = String.escapeSingleQuotes(String.valueOf(claimId));
        String conditions = 'Claim__c = \'' + safeId + '\'';
        return (List<ClaimParticipant__c>) DA_Utility.query(
            FIELDS_PARTICIPANT, OBJECT_PARTICIPANT, conditions, 'Name', null
        );
    }

    /**
     * Récupère les garanties (ClaimCoverage__c) liées à un sinistre.
     */
    public static List<ClaimCoverage__c> getCoveragesByClaimId(Id claimId) {
        if (claimId == null) return new List<ClaimCoverage__c>();
        String safeId    = String.escapeSingleQuotes(String.valueOf(claimId));
        String conditions = 'Claim__c = \'' + safeId + '\'';
        return (List<ClaimCoverage__c>) DA_Utility.query(
            FIELDS_COVERAGE, OBJECT_COVERAGE, conditions, 'Name', null
        );
    }
}