force-app/main/default/objects/Account/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Féminin</fullName>
            </value>
            <value>
                <fullName>Masculin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <formula>HYPERLINK(
    Vehicule__c,
    Vehicule__r.RegistrationNumber__c,
    &quot;_blank&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numéro d’immatriculation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/ClaimParticipant__c.object-meta.xml
<CustomObject>
    <label>Claim Participant</label>
    <nameField>
        <label>Claim Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimParticipant__c/fields/BirthDay__c.field-meta.xml
<CustomField>
    <fullName>BirthDay__c</fullName>
    <label>Date de Naissance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Claim__c.field-meta.xml
<CustomField>
    <fullName>Claim__c</fullName>
    <label>Claim</label>
    <referenceTo>Claim__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>ClaimParticipants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/isDriver__c.field-meta.xml
<CustomField>
    <fullName>isDriver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Participant est conducteur ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/isOwner__c.field-meta.xml
<CustomField>
    <fullName>isOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isOwner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ParticipantAccount__c.field-meta.xml
<CustomField>
    <fullName>ParticipantAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nom et Prénom</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/ParticipantCNI__c.field-meta.xml
<CustomField>
    <fullName>ParticipantCNI__c</fullName>
    <formula>ParticipantAccount__r.CIN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNI</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Passager__c.field-meta.xml
<CustomField>
    <fullName>Passager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant de l&apos;accident</label>
    <referenceTo>Passager__c</referenceTo>
    <relationshipLabel>Claim Participants</relationshipLabel>
    <relationshipName>Claim_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passager assuré</fullName>
            </value>
            <value>
                <fullName>Passager adverse</fullName>
            </value>
            <value>
                <fullName>Autres partie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Sexe__c.field-meta.xml
<CustomField>
    <fullName>Sexe__c</fullName>
    <label>Sexe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Féminin</fullName>
            </value>
            <value>
                <fullName>Masculin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/StateOfPerson__c.field-meta.xml
<CustomField>
    <fullName>StateOfPerson__c</fullName>
    <label>Etat du Participant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indemne</fullName>
            </value>
            <value>
                <fullName>Blessé</fullName>
            </value>
            <value>
                <fullName>Décédé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/TypeContact__c.field-meta.xml
<CustomField>
    <fullName>TypeContact__c</fullName>
    <label>Type de Contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mail</fullName>
            </value>
            <value>
                <fullName>Téléphone</fullName>
            </value>
            <value>
                <fullName>Mail et Téléphone</fullName>
                <default>true</default>
                <label>Mail et Téléphone</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimParticipant__c/fields/Vehicule__c.field-meta.xml
<CustomField>
    <fullName>Vehicule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Véhicule</label>
    <referenceTo>Vehicule__c</referenceTo>
    <relationshipLabel>Participants de l&apos;accident</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicule__c/Vehicule__c.object-meta.xml
<CustomObject>
    <label>Véhicule</label>
    <nameField>
        <displayFormat>Véc-{00000}</displayFormat>
        <label>Numéro de véhicule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Véhicules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicule__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <label>Numéro d&apos;immatriculation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DM005_ClaimParticipant.cls
public with sharing class DM005_ClaimParticipant {

    private static final String CLAIM_PARTICIPANT = 'ClaimParticipant__c';

    private static final String FIELDS =
        'Id, Name, Claim__c, Claim__r.Name, ' +
        'ParticipantAccount__c, ParticipantAccount__r.Name, ' +
        'Roles__c, StateOfPerson__c, ' +
        'Vehicule__c, Vehicule__r.RegistrationNumber__c, ' +
        'BirthDay__c, Sexe__c, Civilite__c, ' +
        'ParticipantCNI__c, TypeContact__c, ' +
        'isDriver__c, isOwner__c, Passager__c';

    public static List<ClaimParticipant__c> getByClaimId(String fields, Id claimId) {
        String queryFields = String.isNotBlank(fields) ? fields : FIELDS;
        String conditions = 'Claim__c = \'' + String.escapeSingleQuotes(String.valueOf(claimId)) + '\'';
        return (List<ClaimParticipant__c>) DA_Utility.query(queryFields, CLAIM_PARTICIPANT, conditions, 'CreatedDate DESC', null);
    }

    public static List<ClaimParticipant__c> getByAccountId(String fields, Id accountId) {
        String queryFields = String.isNotBlank(fields) ? fields : FIELDS;
        String conditions = 'ParticipantAccount__c = \'' + String.escapeSingleQuotes(String.valueOf(accountId)) + '\'';
        return (List<ClaimParticipant__c>) DA_Utility.query(queryFields, CLAIM_PARTICIPANT, conditions, 'CreatedDate DESC', null);
    }

    public static List<ClaimParticipant__c> getByClaimAndRole(String fields, Id claimId, String role) {
        String queryFields = String.isNotBlank(fields) ? fields : FIELDS;
        String safeId = String.escapeSingleQuotes(String.valueOf(claimId));
        String safeRole = String.escapeSingleQuotes(role);
        String conditions = 'Claim__c = \'' + safeId + '\' AND Roles__c = \'' + safeRole + '\'';
        return (List<ClaimParticipant__c>) DA_Utility.query(queryFields, CLAIM_PARTICIPANT, conditions, 'CreatedDate DESC', null);
    }

    public static ClaimParticipant__c getById(String fields, Id recordId) {
        String queryFields = String.isNotBlank(fields) ? fields : FIELDS;
        return (ClaimParticipant__c) DA_Utility.getById(queryFields, CLAIM_PARTICIPANT, recordId);
    }
}