force-app/main/default/objects/Instruction__c/Instruction__c.object-meta.xml
<CustomObject>
    <label>Instruction</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>N° Instruction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Instruction__c/fields/InstructionType__c.field-meta.xml
<CustomField>
    <fullName>InstructionType__c</fullName>
    <label>Type d’instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PEC - Prise en charge</fullName>
            </value>
            <value>
                <fullName>Remboursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Instruction__c/fields/TypeDegat__c.field-meta.xml
<CustomField>
    <fullName>TypeDegat__c</fullName>
    <label>Type de dégât</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Matériel</fullName>
            </value>
            <value>
                <fullName>Corporel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DM_InstructionCoverage.cls
public with sharing class DM_InstructionCoverage {
    
    public static List<Instruction_Coverage__c> getInstructionCoverages(String instructionId) {
            String fields = 'Id, Name, CurrencyIsoCode, ' +'ClaimCoverage__r.Name, ClaimCoverage__r.CodeGarantie__c, ' +
                           'Instruction__r.Name, Instruction__r.InstructionType__c, Instruction__r.TypeDegat__c';
            String conditions = 'Instruction__c = \'' + String.escapeSingleQuotes(instructionId) + '\'';
            String orderBy = 'Name ASC';
            List<SObject> results = DA_Utility.query(fields, 'Instruction_Coverage__c', conditions, orderBy, null);
            System.debug('DM_InstructionCoverage - Instruction ID: ' + instructionId);
            System.debug('DM_InstructionCoverage - Résultats trouvés: ' + results.size());
            return (List<Instruction_Coverage__c>) results;
        
    }
}