force-app/main/default/objects/CaseCoverage__c/CaseCoverage__c.object-meta.xml
<CustomObject>
    <label>Case Coverage</label>
    <nameField>
        <label>Case Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseCoverage__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Coverages</relationshipLabel>
    <relationshipName>CaseCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseCoverage__c/fields/CodeGarantie__c.field-meta.xml
<CustomField>
    <fullName>CodeGarantie__c</fullName>
    <label>Code Garantie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DM009_CaseCoverage.cls
public with sharing class DM009_CaseCoverage {

    private static final String OBJ = 'CaseCoverage__c';
    private static final String FIELDS = 'Id, Name, CodeGarantie__c, Case__c';

    public static List<CaseCoverage__c> getByCaseId(String fields, Id caseId) {
        String queryFields = String.isNotBlank(fields) ? fields : FIELDS;
        String safeId = String.escapeSingleQuotes(String.valueOf(caseId));
        return (List<CaseCoverage__c>) DA_Utility.query(queryFields, OBJ, 'Case__c = \'' + safeId + '\'', 'CreatedDate DESC', null);
    }
}