force-app/main/default/objects/InsurancePolicyCoverage__c/InsurancePolicyCoverage__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy Coverage</label>
    <nameField>
        <displayFormat>COV-{00000}</displayFormat>
        <label>Insurance Policy Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Policy Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InsurancePolicyCoverage__c/fields/InsurancePolicy__c.field-meta.xml
<CustomField>
    <fullName>InsurancePolicy__c</fullName>
    <label>Insurance Policy</label>
    <referenceTo>InsurancePolicy__c</referenceTo>
    <relationshipLabel>Insurance Policy Coverages</relationshipLabel>
    <relationshipName>InsurancePolicyCoverages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DM008_InsurancePolicyCoverage.cls
public with sharing class DM008_InsurancePolicyCoverage {

    private static final String OBJECT_NAME = 'InsurancePolicyCoverage__c';

    public static List<InsurancePolicyCoverage__c> getByPolicyId(String fields, Id policyId) {
        if (policyId == null) return new List<InsurancePolicyCoverage__c>();

        String safeId = String.escapeSingleQuotes(String.valueOf(policyId));
        String conditions = 'InsurancePolicy__c = \'' + safeId + '\'';
        String orderBy = 'CreatedDate ASC';

        return (List<InsurancePolicyCoverage__c>) DA_Utility.query(fields, OBJECT_NAME, conditions, orderBy, null);
    }

}