force-app/main/default/objects/Claim__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/Flags__c.field-meta.xml
<CustomField>
    <fullName>Flags__c</fullName>
    <label>Flags</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sensible</fullName>
            </value>
            <value>
                <fullName>Majeur</fullName>
            </value>
            <value>
                <fullName>Grave</fullName>
            </value>
            <value>
                <fullName>Frauduleux</fullName>
            </value>
            <value>
                <fullName>Douteux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DM006_Claim.cls
public with sharing class DM006_Claim {

    private static final String OBJ = 'Claim__c';

    private static final String FIELDS =
        'Id, Name, Flags__c, Case__c, CreatedDate';

    public static Claim__c getById(String fields, Id claimId) {
        String queryFields = String.isNotBlank(fields) ? fields : FIELDS;
        return (Claim__c) DA_Utility.getById(queryFields, OBJ, claimId);
    }

    public static void updateClaim(Claim__c claim) {
        update claim;
    }
}