force-app/main/default/objects/Claim__c/fields/EvenementAssocie__c.field-meta.xml
<CustomField>
    <fullName>EvenementAssocie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Événement associé</label>
    <referenceTo>Evenement__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim__c/fields/PopupEvenementVu__c.field-meta.xml
<CustomField>
    <fullName>PopupEvenementVu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Popup Evenement Vu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EM006_Evenement.cls
public with sharing class EM006_Evenement {

    public static void upsertEvenement(Evenement__c evt) {
        upsert evt;
    }

    public static void deleteEvenement(Id recordId) {
        DA_Utility.deleteById('Evenement__c', recordId);
    }

    public static void associerEvenement(Id claimId, Id evenementId) {
        update new Claim__c(
            Id                  = claimId,
            EvenementAssocie__c = evenementId,
            PopupEvenementVu__c = true
        );
    }

    public static void marquerPopupVu(Id claimId) {
        update new Claim__c(
            Id                  = claimId,
            PopupEvenementVu__c = true
        );
    }
}